#pragma once

#include <QtGlobal>

#if defined(MESONPROJECTMANAGER_LIBRARY)
#  define MESONPROJECTMANAGERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define MESONPROJECTMANAGERSHARED_EXPORT Q_DECL_IMPORT
#endif
